-- Retro Box Database Schema

CREATE TABLE IF NOT EXISTS teams (
  id SERIAL PRIMARY KEY,
  team_code VARCHAR(6) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS boxes (
  id SERIAL PRIMARY KEY,
  team_id INTEGER REFERENCES teams(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  closed_at TIMESTAMP,
  status VARCHAR(20) DEFAULT 'open',
  retro_number INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS notes (
  id SERIAL PRIMARY KEY,
  box_id INTEGER REFERENCES boxes(id) ON DELETE CASCADE,
  type VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  author_name VARCHAR(100),
  anonymous BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  opened BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS retros (
  id SERIAL PRIMARY KEY,
  box_id INTEGER REFERENCES boxes(id) ON DELETE CASCADE,
  host_client_id VARCHAR(100) NOT NULL,
  current_note_id INTEGER,
  status VARCHAR(20) DEFAULT 'in_retro',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  retro_number INTEGER DEFAULT 1
);
